### ISSUE TITLE
deploy to heroku problem

### ISSUE THREAD

**Issue by yeeeshiuan** [twtrubiks/Deploying-Flask-To-Heroku#2]
先謝謝有這個教學，
我跟著教學作，到deploy的地方，

完成後是500error，
到heroku logs --tail 查看，
注意到有 KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'
網路上查，說是兩個 app = Flask(__name__) 會造成衝突，

我將app.py裡的 app = Flask(__name__) 移除掉，
變成
`... relation "UserData" does not exist`
找不到UserData

我將dbModel.py裡的 app = Flask(__name__) 移除掉，
變成dbModel.py 發生
`NameError: name 'app' is not defined`

還有將 app = Flask(__name__) 抽出，
放到__init__.py裡，
也是有問題...
一直鬼打牆...

我有更動的地方是：runtime.txt 改成python3.6.6
跟 app.config['SQLALCHEMY_DATABASE_URI'] 
改成我的heroku postgres 的位置

**Comment by twtrubiks** [comment]
理論上應該是不會有問題的，因為我近期有嘗試過，應該是沒有問題的，

不過也可能因為套件版本更新導致的問題，其實我看不太懂你的意思@@

500 error 就是很嚴重的錯誤，可能是套件沒安裝成功，或是 db 設定錯誤，

又或是你沒有 migration ，總之，就是要找問題，這樣的資訊我沒辦法幫你解答。

而且為甚麼會有 兩個 app = Flask(name) 呢 ?

"UserData" does not exist ?   這代表你還沒有 migration

建議看我的教學影片跟著做。

**Comment by yeeeshiuan** [comment]
謝謝，
真的沒有migration，
我循著 Flask-Migrate-Tutorial 流程：
`pip install Flask-Migrate`
`python dbModel.py db init`
`python dbModel.py db migrate`
`python dbModel.py db upgrade`
並且將 migrations/ 都加到git 裡
`git add .`
但是我發現，app_run.py 裡的 app = Flask(__name__)
要移掉才能在heroku 正常執行，
不然會有 KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'
最後非常謝謝作者抽空回應，
更非常感謝作者分享這麼多的教學範例和教學影片，
讓無明者在這學習路上有指路明燈
